version: '3.8'

services:
  # The FastAPI Application service
  web:
    build: .
    ports:
      # Map port 8000 on your machine to port 8000 in the container
      - "8000:8000"
    env_file:
      # Load environment variables from the .env file
      - .env

